# Generated by Django 3.2.9 on 2021-12-07 00:25

import Eshop_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=False, verbose_name='موجودیت'),
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Eshop_products.models.upload_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
