# Generated by Django 3.2.9 on 2021-12-07 09:14

import Eshop_products.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0003_auto_20211207_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=Eshop_products.models.upload_image_path, verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
