# Generated by Django 3.2.9 on 2021-12-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0004_auto_20211207_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='برند'),
        ),
    ]
