# Generated by Django 3.2.9 on 2021-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_tag', '0004_remove_tag_products'),
        ('Eshop_products', '0005_alter_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Eshop_tag.Tag'),
        ),
    ]
