# Generated by Django 3.2.9 on 2021-12-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_category', '0001_initial'),
        ('Eshop_products', '0006_products_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='Eshop_category.Category'),
        ),
    ]
