# Generated by Django 3.2.9 on 2021-12-18 16:22

import Eshop_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0007_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=Eshop_products.models.upload_gallery_image_path, verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop_products.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
