# Generated by Django 3.2.9 on 2021-12-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0008_products_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_gallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
