# Generated by Django 3.2.9 on 2022-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_products', '0009_auto_20211219_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
