# Generated by Django 3.2.9 on 2022-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_orders', '0004_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.IntegerField(max_length=100, verbose_name='کد تخفیف(درصد)'),
        ),
    ]
