# Generated by Django 3.2.9 on 2022-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_orders', '0005_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=200, verbose_name='کد تخفیف'),
        ),
    ]
