# Generated by Django 3.2.9 on 2022-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_orders', '0006_alter_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='worth',
            field=models.IntegerField(default=0, max_length=100, verbose_name='درصد تخفیف'),
            preserve_default=False,
        ),
    ]
