# Generated by Django 3.2.9 on 2022-01-03 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_orders', '0007_discount_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='worth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='درصد تخفیف'),
        ),
    ]
