# Generated by Django 3.2.9 on 2022-01-04 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_orders', '0009_alter_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshop_orders.discount', verbose_name='کد تخفیف اعمال شده'),
        ),
    ]
