# Generated by Django 3.2.9 on 2021-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
