# Generated by Django 3.2.9 on 2021-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_tag', '0002_alter_tag_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
