# Generated by Django 3.2.9 on 2021-12-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_tag', '0003_auto_20211211_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
