# Generated by Django 3.2.9 on 2021-12-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_slider', '0002_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(),
        ),
    ]
