# Generated by Django 3.2.9 on 2021-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_slider', '0003_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
