# Generated by Django 3.2.9 on 2021-12-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
