# Generated by Django 3.2.9 on 2021-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_contact', '0003_auto_20211219_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='text',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
