# Generated by Django 3.2.9 on 2021-12-19 16:00

import Eshop_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_setting', '0003_auto_20211219_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to=Eshop_products.models.upload_image_path, verbose_name='لوگو سایت 2'),
        ),
    ]
