# Generated by Django 3.2.9 on 2021-12-30 19:14

import Eshop_setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_setting', '0004_site_setting_logo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Eshop_setting.models.upload_image_path, verbose_name='لوگو سایت'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to=Eshop_setting.models.upload_image_path, verbose_name='لوگو سایت 2'),
        ),
    ]
