# Generated by Django 3.2.9 on 2022-01-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eshop_products', '0010_products_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام و نام خوانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='نظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop_products.products', verbose_name='محصول')),
            ],
        ),
    ]
