# Generated by Django 3.2.9 on 2022-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_comments', '0002_rename_name_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
