# Generated by Django 3.2.9 on 2022-01-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_comments', '0003_comments_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'نظر کاربر', 'verbose_name_plural': 'نظرات کاربران'},
        ),
    ]
